scaleflex_sylius_filerobot:
  filters:
    sylius_admin_product_large_thumbnail: { width: 550, height: 412 }
    sylius_admin_product_small_thumbnail: { width: 150, height: 112 }
    sylius_admin_product_tiny_thumbnail: { width: 64, height: 64 }
    sylius_admin_product_thumbnail: { width: 50, height: 50 }
    sylius_shop_product_tiny_thumbnail: { width: 64, height: 64 }
    sylius_shop_product_small_thumbnail: { width: 150, height: 112 }
    sylius_shop_product_thumbnail: { width: 260, height: 260 }
    sylius_shop_product_large_thumbnail: { width: 550, height: 412 }
